spring:
  profiles:
    active: dev
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username:
    password:
  h2:
    console:
    enabled: false
    path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
ionix:
  encryption-configuration:
    secret: "ionix123456"
info:
  project:
    title: "User Web Application"
    description: "An user web application"
    version: "1.0.0"
